spring.application.name=api-gateway

# =========================
# Order Service Route
# =========================
spring.cloud.gateway.routes[0].id=order-service
spring.cloud.gateway.routes[0].uri=${ORDER_SERVICE_URI:lb://ORDER-SERVICE}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/orders/**

spring.cloud.gateway.routes[0].filters[0]=StripPrefix=2

spring.cloud.gateway.routes[0].filters[1].name=Authentication
spring.cloud.gateway.routes[0].filters[1].args.enabled=true

spring.cloud.gateway.routes[0].filters[2].name=Authorization
spring.cloud.gateway.routes[0].filters[2].args.allowedRoles[0]=USER
spring.cloud.gateway.routes[0].filters[2].args.allowedRoles[1]=ADMIN
spring.cloud.gateway.routes[0].filters[2].args.allowedRoles[2]=SUPER_ADMIN


# =========================
# Inventory Service Route
# =========================
spring.cloud.gateway.routes[1].id=inventory-service
spring.cloud.gateway.routes[1].uri=${INVENTORY_SERVICE_URI:lb://INVENTORY-SERVICE}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/inventory/**

spring.cloud.gateway.routes[1].filters[0]=StripPrefix=2
spring.cloud.gateway.routes[1].filters[1]=AddRequestHeader=X-Custom-Header, Anuj

spring.cloud.gateway.routes[1].filters[2].name=Authentication
spring.cloud.gateway.routes[1].filters[2].args.enabled=true

spring.cloud.gateway.routes[1].filters[3].name=Authorization
spring.cloud.gateway.routes[1].filters[3].args.allowedRoles[0]=USER
spring.cloud.gateway.routes[1].filters[3].args.allowedRoles[1]=ADMIN
spring.cloud.gateway.routes[1].filters[3].args.allowedRoles[2]=SUPER_ADMIN


# =========================
# JWT
# =========================
jwt.secretKey=mysupersecretkeymysupersecretkey12345
