ORDER_SERVICE_URI=http://order-service:9021
INVENTORY_SERVICE_URI=http://inventory-service:9011
SHIPPING_SERVICE_URI=http://shipping-service:4321
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
