spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hemanth-coder-638/ecommerce-config-server
          username: Hemanth-coder-638
          password: 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
          default-label: main

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
